#!/bin/bash -x

echo "%%% This file is generated by the Makefile." > vc.tex
git log -1 --date=short --format="format:\\newcommand{\\githash}{%h}\\newcommand{\\gitdate}{%ad}\\newcommand{\\gitauthor}{%an}" >> vc.tex

# Build the paper
tectonic article/ms.tex -shell-escape
